config/routes.rb
Imdb::Application.routes.draw do
  resources :categories


  # resources :ratings

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  scope 'api' do
    resources :movies, only: [:index, :create]
  end
  resources :movies, except: [:index, :create] do
    resources :ratings
  end

  root to: 'main#index'
  # match '*path' => 'main#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :movies

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :text, :title, :category

  validates_presence_of :title
  validates_uniqueness_of :title

  has_many :ratings
  belongs_to :category

  include Tire::Model::Search
  include Tire::Model::Callbacks
  index_name INDEX_NAME unless Rails.env.development?

  def self.search(params)
    tire.search(page: params[:page], per_page: params[:per_page]) do
      query { string params[:query], default_operator: 'AND' } if params[:query].present?
      filter :term, rating_avg: params[:rating_avg] if params[:rating_avg].present?
      filter :term, category_id: params[:category_id] if params[:category_id].present?
      sort { by :created_at, 'desc'} if params[:query].blank?
      facet 'rating' do
        terms :rating_avg
      end
      facet 'category' do
        terms :category_id
      end
      # raise to_curl
    end
  end

  def rated_by?(user)
    rated = false
    ratings.each do |r|
      rated = r.user == user
      break if rated
    end
    rated
  end

  def to_indexed_json
    to_json(methods: [:rating_count, :rating_avg, :category_id, :category_name])
  end

  def rating_count
    ratings.size
  end

  def rating_avg
    ratings.average(:number).to_i
  end

  def category_id
    category.try(:id) || '-1'
  end

  def category_name
    category.try(:name)
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :movie, :number, :user

  belongs_to :movie
  belongs_to :user

  validates_presence_of :user
  validates_presence_of :movie
  validates_numericality_of :number
  validates_inclusion_of :number, in: 0..5
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation

  validates_presence_of :email
  validates_uniqueness_of :email

  has_one :rating
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue
    session[:user_id] = nil
    @current_user = nil
  end
  helper_method :current_user

  def logged_in?
    Rails.logger.error "DEBUG #{session.pretty_inspect}"
    if current_user.blank?
      render json: 'unauthorized access', status: :forbidden
      false
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    gon.movies = Movie.search(params)
    gon.ratings = gon.movies.facets['rating']['terms']
    gon.total = gon.movies.total
    gon.categories = Category.all
    gon.categoryFacets = gon.movies.facets['category']['terms']
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :logged_in?, except: [:index, :show]
  respond_to :json, :html

  def index
    @movies = Movie.search(params)
    gon.movies = @movies
    gon.ratings = @movies.facets['rating']['terms']
    @total = @movies.total
    gon.total = @total
    gon.categories = Category.all
    gon.categoryFacets = @movies.facets['category']['terms']
    respond_with @movies
  end

  def show
    # respond_with Movie.find(params[:id])
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    params[:movie][:category] = Category.find(params[:movie][:category][:id]) rescue nil
    respond_with Movie.create(params[:movie])
  end

  def update
    # respond_with Movie.update(params[:id], params[:movie])
    @movie = Movie.find(params[:id])
    if @movie.save
      redirect_to movie_path(@movie)
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    respond_to do |format|
      format.json
      format.html do
        redirect_to root_path, notice: 'Der Film wurde geloescht'
      end
    end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index

  end

  def new
    @rating = Movie.find(params[:movie_id]).ratings.build
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @rating = @movie.ratings.build(params[:rating].merge(user: current_user))
    if @movie.save
      redirect_to @movie
    else
      render 'new'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Angemeldet'
    else
      flash[:alert] = 'E-Mail oder Passwort sind falsch!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged Out'
  end
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
  respond_to :html, :json

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Vielen Dank für die Anmeldung! Sie sind jetzt automatisch schon eingelogt.'
    else
      render 'new'
    end
  end
end

app/views/layouts/application.html.haml
!!!html
%html
  %head
    %title New Movie DataBase
    /[if lt IE 9]
      %script{src: "http://html5shim.googlecode.com/svn/trunk/html5.js", type: "text/javascript"}
    = stylesheet_link_tag    "application", media: "all"
    = csrf_meta_tags
    = include_gon
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{data: {toggle: "collapse", target: ".nav-collapse"}}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href:"/#"} NMDb
          .nav-collapse
            %ul.nav
              %li= link_to "Movies", '/#movies'
          .pull-right
            - if current_user
              = link_to 'Abmelden', logout_path, class: 'btn'
            - else
              = link_to 'Registrieren', signup_path, class: 'btn btn-success'
              = link_to 'Anmelden', login_path, class: 'btn btn-warning'
    .container
      - flash.each do |name, msg|
        .alert{class: "alert-#{ name == :notice ? "success" : "error"}"}
          %a.close{data: {dismiss: "alert"}}×
          = msg
      .row
        .span12
          #container
            = yield

    = javascript_include_tag "application"
    :javascript
      window.current_user = #{current_user.present?}

app/views/movies/edit.html.haml
%h1 "#{@movie.title}" bearbeiten

= form_for @movie, html: {class: 'form-horizontal'} do |f|
  .control-group
    = f.label :title, 'Titel', class: 'control-label'
    .controls
      = f.text_field :title, class: 'span5'
  .control-group
    = f.label :text, 'Beschreibung', class: 'control-label'
    .controls
      = f.text_area :text, class: 'span5', rows: 8
  .control-group
    .controls
      = f.submit 'Speichern', class: 'btn btn-success'
      = link_to 'Abbrechen', movie_path(@movie), class: 'btn btn-warning'

= link_to content_tag(:i, '', class: 'icon-arrow-left') + " Zurück zum Film '#{@movie.title}'", movie_path(@movie), class: 'btn'

app/views/movies/show.html.haml
- desc = @movie.text.present? ? @movie.text : content_tag(:span, 'nicht vorhanden', class: 'muted')
%h1= @movie.title
%dl.dl-horizontal
  %dt Beschreibung
  %dd= desc
  %dt &#216; Bewertung
  %dd= render 'shared/star', stars: @movie.rating_avg

- if current_user
  .movie-meta
    = link_to 'Bearbeiten', edit_movie_path(@movie), class: 'btn'
    = link_to 'Loeschen', movie_path(@movie), method: :delete, confirm: 'Wollen Sie den Film wirklich loeschen?', class: 'btn btn-danger'

%h3 #{@movie.rating_count} Bewertungen
- if current_user && !@movie.rated_by?(current_user)
  = link_to content_tag(:i, '', class: 'icon-plus').to_s + ' Bewertung abbgeben', new_movie_rating_path(@movie), class: 'btn'
%table.table
  - @movie.ratings.each do |rating|
    = render 'shared/rating', rating: rating


= link_to content_tag(:i, '', class: 'icon-arrow-left') + " Zurück zur Übersicht", '/', class: 'btn'

app/views/ratings/new.html.haml
%h1 Neue Bewertung für den Film '#{@rating.movie.title}'

= form_for [@rating.movie, @rating], html: {class: 'form-horizontal'} do |f|
  - if @rating.errors.any?
    .alert.alert-error
      %a.close{data: {dismiss:"alert"}}×
      - @rating.errors.full_messages.each do |message|
        = message
        %br/
  .control-group
    = f.label 'Bewertung', class: 'control-label'
    .controls
      = f.select :number, 1..5
  .control-group
    .controls
      = f.submit 'Speichern', class: 'btn btn-success'
      = link_to 'Abbrechen', movie_path(@rating.movie), class: 'btn btn-warning'

app/views/shared/_rating.html.haml
%tr
  %td= rating.user.email
  %td
    = render 'shared/star', stars: rating.number

app/views/shared/_star.html.haml
.stars{class: "s-#{stars}"}

app/views/users/new.html.haml
%h1 Registrierung

= form_for @user, html: {class: 'form-horizontal'} do |f|
  - if @user.errors.any?
    .alert.alert-error
      %a.close{data: {dismiss:"alert"}}×
      - @user.errors.full_messages.each do |message|
        = message
        %br/
  .control-group
    = f.label :email, 'E-Mail', class: 'control-label'
    .controls
      = f.text_field :email
  .control-group
    = f.label :password, 'Passwort', class: 'control-label'
    .controls
      = f.password_field :password
  .control-group
    = f.label :password_confirmation, 'Passwortbestätigung', class: 'control-label'
    .controls
      = f.password_field :password_confirmation
  .control-group
    .controls
      = f.submit 'Anmelden', class: 'btn'